name: Python Code Quality

on:
  workflow_call:  # Makes this workflow reusable
  pull_request:
    paths:
      - '**.py'

jobs:
  check-python:
    name: Check for Python files
    runs-on: ubuntu-latest
    outputs:
      has_python: ${{ steps.check.outputs.has_python }}
    steps:
      - uses: actions/checkout@v4
      
      - id: check
        name: Check for Python files
        run: |
          if find . -name "*.py" -type f -print -quit | grep -q .; then
            echo "has_python=true" >> $GITHUB_OUTPUT
          else
            echo "has_python=false" >> $GITHUB_OUTPUT
          fi

  quality:
    name: Code Quality
    needs: check-python
    if: needs.check-python.outputs.has_python == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your pyproject.toml
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction

      - name: Run black
        run: poetry run black --check --diff .
        
      - name: Run mypy
        run: poetry run mypy --strict .
        
      - name: Run ruff
        run: poetry run ruff check .