name: Python Code Quality

on:
  workflow_call:  # Makes this workflow reusable
  pull_request:
    paths:
      - '**.py'

jobs:
  check-python:
    name: Check for Python files
    runs-on: ubuntu-latest
    outputs:
      has_python: ${{ steps.check.outputs.has_python }}
    steps:
      - uses: actions/checkout@v4
      
      - id: check
        name: Check for Python files
        run: |
          if find . -name "*.py" -type f -print -quit | grep -q .; then
            echo "has_python=true" >> $GITHUB_OUTPUT
          else
            echo "has_python=false" >> $GITHUB_OUTPUT
          fi

  quality:
    name: Code Quality
    needs: check-python
    if: needs.check-python.outputs.has_python == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy black
          # Install project dependencies if they exist
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install type stubs for common libraries
          pip install types-requests types-setuptools
          
      - name: Run black
        run: black --check --diff .
        
      - name: Run mypy
        run: mypy --strict .